export default [
  {
    'gameId': 8820,
    'name': '1 Can 2 Can',
    'shortDescription': 'Short Description',
    'slug': '1-can-2-can',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'NYX Gaming',
    'inMaintenance': false
  },
  {
    'gameId': 9718,
    'name': '1429 Uncharted Seas',
    'shortDescription': 'Short Description',
    'slug': '1429-uncharted-seas',
    'suggestedHeight': 9,
    'suggestedWidth': 16,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'NYX Gaming',
    'inMaintenance': false
  },
  {
    'gameId': 7989,
    'name': '2 Million B.C.',
    'shortDescription': 'Short Description',
    'slug': '2-million-bc',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': '3D Slots',
    'vendor': 'BetSoft',
    'inMaintenance': false
  },
  {
    'gameId': 8405,
    'name': '300 Shields',
    'shortDescription': 'Short Description',
    'slug': '300-shields',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'NYX Gaming',
    'inMaintenance': false
  },
  {
    'gameId': 10003,
    'name': '4 Seasons',
    'shortDescription': 'Short Description',
    'slug': '4-seasons',
    'suggestedHeight': 9,
    'suggestedWidth': 16,
    'description': 'Description',
    'category': '',
    'gameType': '3D Slots',
    'vendor': 'BetSoft',
    'inMaintenance': false
  },
  {
    'gameId': 9284,
    'name': '5 Knights',
    'shortDescription': 'Short Description',
    'slug': '5-knights',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'NYX Gaming',
    'inMaintenance': false
  },
  {
    'gameId': 7100,
    'name': '5 Reel Drive',
    'shortDescription': 'Short Description',
    'slug': '5-reel-drive',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'Microgaming',
    'inMaintenance': false
  },
  {
    'gameId': 7856,
    'name': '5x Magic',
    'shortDescription': 'Short Description',
    'slug': '5x-magic',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Classic Slots',
    'vendor': 'Play N Go',
    'inMaintenance': false
  },
  {
    'gameId': 7277,
    'name': '7 Gold Scratch',
    'shortDescription': 'Short Description',
    'slug': '7-gold-scratch',
    'suggestedHeight': 4,
    'suggestedWidth': 3,
    'description': 'Description',
    'category': '',
    'gameType': 'Other',
    'vendor': 'Netent',
    'inMaintenance': false
  },
  {
    'gameId': 7990,
    'name': '7th Heaven',
    'shortDescription': 'Short Description',
    'slug': '7th-heaven',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': '3D Slots',
    'vendor': 'BetSoft',
    'inMaintenance': false
  },
  {
    'gameId': 5154,
    'name': 'A Night in Paris JP',
    'shortDescription': 'Short Description',
    'slug': 'a-night-in-paris-jp',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': '3D Slots',
    'vendor': 'BetSoft',
    'inMaintenance': false
  },
  {
    'gameId': 8815,
    'name': 'A While on the Nile',
    'shortDescription': 'Short Description',
    'slug': 'a-while-on-the-nile',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'NYX Gaming',
    'inMaintenance': false
  },
  {
    'gameId': 7205,
    'name': 'Ace',
    'shortDescription': 'Short Description',
    'slug': 'ace',
    'suggestedHeight': 4,
    'suggestedWidth': 3,
    'description': 'Description',
    'category': '',
    'gameType': 'Other',
    'vendor': 'Netent',
    'inMaintenance': false
  },
  {
    'gameId': 7860,
    'name': 'Ace of Spades',
    'shortDescription': 'Short Description',
    'slug': 'ace-of-spades',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Classic Slots',
    'vendor': 'Play N Go',
    'inMaintenance': false
  },
  {
    'gameId': 7984,
    'name': 'Aces and Eights',
    'shortDescription': 'Short Description',
    'slug': 'aces-and-eights',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Poker',
    'vendor': 'Microgaming',
    'inMaintenance': false
  },
  {
    'gameId': 7266,
    'name': 'Aces and Faces',
    'shortDescription': 'Short Description',
    'slug': 'aces-and-faces',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Poker',
    'vendor': 'Microgaming',
    'inMaintenance': false
  },
  {
    'gameId': 7131,
    'name': 'Adventure Palace',
    'shortDescription': 'Short Description',
    'slug': 'adventure-palace',
    'suggestedHeight': 9,
    'suggestedWidth': 16,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'Microgaming',
    'inMaintenance': false
  },
  {
    'gameId': 9633,
    'name': 'Adventure Palace HD',
    'shortDescription': 'Short Description',
    'slug': 'adventure-palace-hd',
    'suggestedHeight': 9,
    'suggestedWidth': 16,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'Microgaming',
    'inMaintenance': false
  },
  {
    'gameId': 8307,
    'name': 'After Night Falls',
    'shortDescription': 'Short Description',
    'slug': 'after-night-falls',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': '3D Slots',
    'vendor': 'BetSoft',
    'inMaintenance': false
  },
  {
    'gameId': 7160,
    'name': 'Age of Discovery',
    'shortDescription': 'Short Description',
    'slug': 'age-of-discovery',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Exploration, adventure and mystery, the Age of Discovery Video Slot encompasses it all! Go back in time to when explorers sailed across the uncharted ocean, using only the stars and rudimentary maps as their guide as they sailed into the sunset towards unknown lands of secret treasures and unwritten histories. ',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'Microgaming',
    'inMaintenance': false
  },
  {
    'gameId': 7132,
    'name': 'Agent Jane Blonde',
    'shortDescription': 'Short Description',
    'slug': 'agent-jane-blonde',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'Microgaming',
    'inMaintenance': false
  },
  {
    'gameId': 7062,
    'name': 'Alaskan Fishing',
    'shortDescription': 'Short Description',
    'slug': 'alaskan-fishing',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Get your pole and lures ready because the fish are biting in Alaskan Fishing! Catch some salmon in the Fly Fishing Bonus and win up to 75 times your total bet! Three or more tackle boxes will take you to the free spin bonus, where all wins are doubled!',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'Microgaming',
    'inMaintenance': false
  },
  {
    'gameId': 7957,
    'name': 'Alaxe in Zombieland',
    'shortDescription': 'Short Description',
    'slug': 'alaxe-in-zombieland',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'Microgaming',
    'inMaintenance': false
  },
  {
    'gameId': 7050,
    'name': 'Alien Robots',
    'shortDescription': 'Short Description',
    'slug': 'alien-robots',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'Netent',
    'inMaintenance': false
  },
  {
    'gameId': 8676,
    'name': 'Aliens',
    'shortDescription': 'Short Description',
    'slug': 'aliens',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Get your adrenaline pumping in this full on action game with amazing 3D graphics. Scan infested premises for Alien activity and shoot through waves of Alien attacks to reach the Queen Hive where massive cash rewards await. In cooperation with 20th Century Fox this exciting game has 3 levels, wild substitutions, re-spins and collectible multipliers. ',
    'category': '',
    'gameType': 'Video Slots',
    'vendor': 'Netent',
    'inMaintenance': false
  },
  {
    'gameId': 9903,
    'name': 'Alkemor\'s Tower',
    'shortDescription': 'Short Description',
    'slug': 'alkemors-tower',
    'suggestedHeight': 9,
    'suggestedWidth': 16,
    'description': 'Description',
    'category': '',
    'gameType': '3D Slots',
    'vendor': 'BetSoft',
    'inMaintenance': false
  },
  {
    'gameId': 7410,
    'name': 'All Aces Poker',
    'shortDescription': 'Short Description',
    'slug': 'all-aces-poker',
    'suggestedHeight': 3,
    'suggestedWidth': 4,
    'description': 'Description',
    'category': '',
    'gameType': 'Video Poker',
    'vendor': 'Microgaming',
    'inMaintenance': false
  }
]
